#ifndef RUST_ENUM_INCLUDE_RUST_ENUM_VARIANT_DETAIL_FWD_VARIANT_FWD_HPP
#define RUST_ENUM_INCLUDE_RUST_ENUM_VARIANT_DETAIL_FWD_VARIANT_FWD_HPP

namespace rust {
template <class...>
class variant;
}

#endif  // RUST_ENUM_INCLUDE_RUST_ENUM_VARIANT_DETAIL_FWD_VARIANT_FWD_HPP
